import Head from 'next/head'
import Menu from '../components/Menu'
import Header from '../components/Header'
export default function Home() {
  return (
    <div className='bg-[#191923]'>
      <div className='container mx-auto p-4 relative overflow-hidden '>
        <Head>
          <title>Портфолио</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Menu />
        <Header />
      </div>
    </div>
  )
}
